version: "3.9"
services:
  web:
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TOKEN=${TOKEN}
    build: backend/
    ports:
      - "5001:8000"
    depends_on:
      - postgres
    command: /entrypoint.sh
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: "postgres:alpine"
    ports:
      - "5432:5432"