mapping_class = {-1:'Computer Science - General',
                 0: 'Machine Leaning - Urban Control',
                 1: 'Mathematics',
                 2: 'Medicine - Sport',
                 3: 'Medicine - Disease',
                 4: 'Computer Science - Programming',
                 5: 'Machine Leaning - Unsupervised Learining',
                 6: 'CyberSecurity',
                 7: 'Computer Science - Data Information',
                 8: 'Computer Science - General',
                 9: 'Computer Science - Systems',
                 10: 'Computer Science - Energy Control',
                 11: 'Games',
                 12: 'Computer Science - General',
                 13: 'Mobiles & Robots',
                 14: 'Computer Science - Particle swarm optimization',
                 15: 'Mathematics - Graphs',
                 16: 'Computer Science - Wireless Networks',
                 17: 'Image & Video',
                 18: 'Computer Science - General',
                 19: 'Computer Science - Radio',
                 20: 'Machine Leaning - NLP',
                 21: 'Mathematics - Statistics',
                 22: 'Computer Science - Cloud Services',
                 23: 'Medicine - Health',
                 24: 'Social',
                 25: 'Mathematics - Statistics',
                 26: 'Mathematics - General',
                 27: 'Computer Science - Optimization',
                 28: 'Computer Science - Software Development'
}

mapping_multi_class = {
                -1: 'Computer Science',
                 0: 'Machine Leaning',
                 1: 'Mathematics',
                 2: 'Sport',
                 3: 'Health',
                 4: 'Computer Science',
                 5: 'Machine Leaning',
                 6: 'CyberSecurity',
                 7: 'Computer Science',
                 8: 'Computer Science',
                 9: 'Computer Science',
                 10: 'Computer Science',
                 11: 'Games',
                 12: 'Computer Science',
                 13: 'Mobiles & Robots',
                 14: 'Computer Science',
                 15: 'Mathematics',
                 16: 'Computer Science',
                 17: 'Image & Video',
                 18: 'Computer Science',
                 19: 'Computer Science',
                 20: 'Machine Leaning',
                 21: 'Mathematics',
                 22: 'Computer Science',
                 23: 'Health',
                 24: 'Social',
                 25: 'Mathematics',
                 26: 'Mathematics',
                 27: 'Computer Science',
                 28: 'Computer Science'
}